logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
spring:
  application:
    name: ticket-management

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    out-of-order: false

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate: 
        default_batch_fetch_size: 15

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000  # 1 sec
          multiplier: 2.0         # Double each time
          max-interval: 60000
          default-requeue-rejected: false

jwt:
  secret: ${JWT_SECRET:}
