-- adding schedular

CREATE TABLE schedulars(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    periodicity BIGINT NULL
);